//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int Id { get; set; }
        public double Price { get; set; }
        public System.DateTime OrderDate { get; set; }
        public System.DateTime ArrivalDate { get; set; }
        public long PaymentCardAccountNumber { get; set; }
        public long CustomerJMBG { get; set; }
        public int OnlineCartId { get; set; }
    
        public virtual PaymentCard PaymentCard { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual OnlineCart OnlineCart { get; set; }
    }
}
