//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int Id { get; set; }
        public int FactoryId { get; set; }
        public Nullable<long> CustomerJMBG { get; set; }
        public string Name { get; set; }
        public Nullable<int> OnlineCartId { get; set; }
        public double Price { get; set; }
    
        public virtual Factory Factory { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual OnlineCart OnlineCart { get; set; }
    }
}
